#! /bin/bash

cp -r /var/tmp/ghost-plotjuggler-ros/* $VEXU_HOME
rm -r /var/tmp/ghost-plotjuggler-ros

if [[ ! -f "$VEXU_HOME/build/.built_by" ]]; then
    echo "colcon" > $VEXU_HOME/build/.built_by
fi
